import type { MapData } from "./types";

// Image assets live under /public and are referenced by URL string:
//   perk icons  → /public/images/perks/icons/<name>.webp   (marker icon)
//   in-game pics → /public/images/perks/ingame/<name>.png  (reveal lightbox)
// Drop a file in the folder and point a marker at it — no imports needed.

// ─────────────────────────────────────────────────────────────────────────
//  Kowakujo — main map data
//
//  Positions are percent of the image (0–100). Tip: enable the cursor-coords
//  overlay (NEXT_PUBLIC_SHOW_COORDS=true) to read exact percentages by
//  hovering, or use the Draw tool for zone outlines.
// ─────────────────────────────────────────────────────────────────────────

export const kowakujo: MapData = {
  id: "kowakujo",
  name: "Kowakujo",
  image: "/maps/kowakujo_main_map.png",
  imageSize: { width: 2912, height: 2912 },

  // Floors, lowest-to-highest. First entry (ground) is the default for any
  // area without an explicit `floor`. Add "roof" here when roof areas arrive.
  floors: [
    { id: "ground", label: "Ground" },
    { id: "upper", label: "Upper" },
  ],

  categories: [
    {
      id: "perk",
      label: "Perk Machines",
      color: "#22d3ee",
      kind: "icon",
      glyph: "🥤",
      defaultVisible: true,
      description: "Perk-a-Cola vending machines.",
    },
    {
      id: "utility",
      label: "Pack-a-Punch",
      color: "#f59e0b",
      kind: "icon",
      glyph: "P",
      defaultVisible: true,
      description: "Pack-a-Punch machine.",
    },
    {
      id: "box",
      label: "Mystery Box",
      color: "#a855f7",
      kind: "icon",
      glyph: "❓",
      defaultVisible: true,
      description: "Possible Mystery Box spawn locations.",
    },
    {
      id: "wallbuy",
      label: "Wall Buys",
      color: "#84cc16",
      kind: "icon",
      glyph: "🔫",
      defaultVisible: false,
      description: "Wall-mounted weapon purchases.",
    },
    {
      id: "spawn",
      label: "Spawn / Exfil",
      color: "#ef4444",
      kind: "icon",
      glyph: "🚩",
      defaultVisible: true,
      description: "Player spawn and exfil points.",
    },
    {
      id: "ee",
      label: "Easter Egg Steps",
      color: "#ec4899",
      kind: "step",
      defaultVisible: true,
      description: "Numbered main-quest step locations.",
    },
  ],

  // ── Icons / markers ─────────────────────────────────────────────────────
  // Start fresh — add real markers here, e.g.:
  //   { id: "perk-jug", categoryId: "perk", label: "Juggernog",
  //     position: { x: 31.2, y: 58.7 }, note: "…", revealImage: "/maps/…png" }
  // Read positions off the live cursor overlay (NEXT_PUBLIC_SHOW_COORDS=true).
  markers: [
    // Pack-a-Punch lives in the utility category (it isn't a perk).
    {
      id: "util-pack-a-punch",
      categoryId: "utility",
      label: "Pack-a-Punch",
      position: { x: 59.7, y: 7.9 },
      icon: "/images/perks/icons/packapunch.png",
      revealImage: "/images/perks/ingame/packapunch.png",
    },

    // Perks. `icon` = icons/<name> (marker), `revealImage` = ingame/<name>.png.
    {
      id: "perk-melee-macchiato",
      categoryId: "perk",
      floor: "ground",
      label: "Melee Macchiato",
      position: { x: 14.9, y: 56.4 },
      icon: "/images/perks/icons/meleemacchiato.webp",
      revealImage: "/images/perks/ingame/meleemacchiato.png",
    },
    {
      id: "perk-elemental-pop",
      categoryId: "perk",
      floor: "ground",
      label: "Elemental Pop",
      position: { x: 56.2, y: 18.7 },
      icon: "/images/perks/icons/elementalpop.webp",
      revealImage: "/images/perks/ingame/elementalpop.png",
    },
    {
      id: "perk-mule-kick",
      categoryId: "perk",
      floor: "ground",
      label: "Mule Kick",
      position: { x: 47.8, y: 19.5 },
      icon: "/images/perks/icons/mulekick.webp",
      revealImage: "/images/perks/ingame/mulekick.png",
    },
    {
      id: "perk-vulture-aid",
      categoryId: "perk",
      floor: "ground",
      label: "Vulture Aid",
      position: { x: 47.2, y: 9 },
      icon: "/images/perks/icons/vultureaid.webp",
      revealImage: "/images/perks/ingame/vultureaid.png",
    },
    {
      id: "perk-phd-flopper",
      categoryId: "perk",
      floor: "ground",
      label: "PHD Flopper",
      position: { x: 39.1, y: 33.3 },
      icon: "/images/perks/icons/phdflopper.webp",
      revealImage: "/images/perks/ingame/phdflopper.png",
    },
    {
      id: "perk-der-wunderfizz",
      categoryId: "perk",
      floor: "ground",
      label: "Der Wunderfizz",
      position: { x: 43.3, y: 36 },
      icon: "/images/perks/icons/derwunderfizz.png",
      revealImage: "/images/perks/ingame/derwunderfizz.png",
    },
    {
      id: "perk-juggernog",
      categoryId: "perk",
      floor: "ground",
      label: "Juggernog",
      position: { x: 56.4, y: 41.3 },
      icon: "/images/perks/icons/juggernog.webp",
      revealImage: "/images/perks/ingame/juggernog.png",
    },
    {
      id: "perk-death-perception",
      categoryId: "perk",
      floor: "ground",
      label: "Death Perception",
      position: { x: 28.4, y: 80.8 },
      icon: "/images/perks/icons/deathperception.webp",
      revealImage: "/images/perks/ingame/deathperception.png",
    },
    {
      id: "perk-stamin-up",
      categoryId: "perk",
      floor: "ground",
      label: "Stamin-Up",
      position: { x: 53.1, y: 76 },
      icon: "/images/perks/icons/staminup.webp",
      revealImage: "/images/perks/ingame/staminup.png",
    },
    {
      id: "perk-quick-revive",
      categoryId: "perk",
      floor: "ground",
      label: "Quick Revive",
      position: { x: 57.7, y: 92.9 },
      icon: "/images/perks/icons/quickrevive.webp",
      revealImage: "/images/perks/ingame/quickrevive.png",
    },
    {
      id: "perk-speed-cola",
      categoryId: "perk",
      floor: "ground",
      label: "Speed Cola",
      position: { x: 58, y: 67.2 },
      icon: "/images/perks/icons/speedcola.webp",
      revealImage: "/images/perks/ingame/speedcola.png",
    },
    {
      id: "perk-wisp-tea",
      categoryId: "perk",
      floor: "ground",
      label: "Wisp Tea",
      position: { x: 79.7, y: 88.7 },
      icon: "/images/perks/icons/wisptea.webp",
      revealImage: "/images/perks/ingame/wisptea.png",
    },
    {
      id: "perk-double-tap",
      categoryId: "perk",
      floor: "ground",
      label: "Double Tap",
      position: { x: 88.8, y: 53.1 },
      icon: "/images/perks/icons/doubletap.webp",
      revealImage: "/images/perks/ingame/doubletap.png",
    },
  ],

  // ── Named areas (text labels) ───────────────────────────────────────────
  // `position` is the centre of the text. Use "\n" to wrap. `outline` (plotted
  // with the Draw tool) draws a colored zone border linked to the label color.
  areas: [
    {
      id: "central-courtyard",
      label: "Central\nCourtyard",
      position: { x: 52.5, y: 48.7 },
      color: "#f59e0b",
      outline: [
        { x: 43.6, y: 42.2 },
        { x: 55.2, y: 40.1 },
        { x: 56.5, y: 41.1 },
        { x: 57.4, y: 40.3 },
        { x: 59.6, y: 42.3 },
        { x: 59, y: 43.2 },
        { x: 63.3, y: 47.3 },
        { x: 62.8, y: 49 },
        { x: 63.4, y: 50.6 },
        { x: 64.4, y: 51.6 },
        { x: 64.7, y: 51.5 },
        { x: 66.5, y: 53.2 },
        { x: 64, y: 55.8 },
        { x: 61.1, y: 53 },
        { x: 57.2, y: 56.7 },
        { x: 44.3, y: 56.5 },
        { x: 44.1, y: 48.7 },
        { x: 43.7, y: 45.1 },
        { x: 42.8, y: 44.8 },
        { x: 42.5, y: 42.8 },
      ],
    },
    {
      id: "kitchens",
      label: "Kitchens",
      position: { x: 78.9, y: 52.2 },
      color: "#38bdf8",
      outline: [
        { x: 68.1, y: 51.8 },
        { x: 63.9, y: 55.8 },
        { x: 63.6, y: 56.2 },
        { x: 65.8, y: 58.4 },
        { x: 67.5, y: 57.1 },
        { x: 70, y: 55.9 },
        { x: 72.6, y: 55.9 },
        { x: 72.8, y: 56.9 },
        { x: 77.4, y: 59.5 },
        { x: 77.3, y: 60.2 },
        { x: 82.7, y: 61.7 },
        { x: 81.3, y: 67.5 },
        { x: 85.4, y: 68.5 },
        { x: 90.3, y: 50.9 },
        { x: 86, y: 49.9 },
        { x: 87.6, y: 44.2 },
        { x: 79.5, y: 42 },
        { x: 75.4, y: 41 },
        { x: 73.7, y: 47.7 },
        { x: 73.3, y: 49.9 },
        { x: 71.9, y: 49.7 },
        { x: 71.8, y: 51.9 },
        { x: 68.1, y: 51.8 },
      ],
    },
    {
      id: "outer-ward",
      label: "Outer\nWard",
      position: { x: 52.8, y: 88.6 },
      color: "#a78bfa",
      outline: [
        { x: 46.5, y: 84 },
        { x: 47.5, y: 87.3 },
        { x: 47.3, y: 92.5 },
        { x: 47.2, y: 93.9 },
        { x: 47.9, y: 95.9 },
        { x: 50.2, y: 97 },
        { x: 52.2, y: 97.2 },
        { x: 55.3, y: 96 },
        { x: 56.7, y: 94.4 },
        { x: 58.5, y: 92.5 },
        { x: 59.5, y: 91.2 },
        { x: 59.8, y: 89.5 },
        { x: 59.8, y: 86.3 },
        { x: 62, y: 84.9 },
        { x: 61, y: 81.9 },
        { x: 60.1, y: 82 },
        { x: 49.5, y: 82.5 },
        { x: 46.5, y: 84 },
      ],
    },
    {
      id: "gatehouse",
      label: "Gatehouse",
      position: { x: 61.6, y: 76 },
      color: "#f472b6",
      outline: [
        { x: 57.3, y: 82.1 },
        { x: 60.1, y: 81.9 },
        { x: 60.1, y: 79.9 },
        { x: 64, y: 79.8 },
        { x: 64.4, y: 79.1 },
        { x: 65.5, y: 78.9 },
        { x: 65.6, y: 79.2 },
        { x: 69.4, y: 79.3 },
        { x: 69.7, y: 78.8 },
        { x: 70.1, y: 78.7 },
        { x: 70.1, y: 74.4 },
        { x: 65.5, y: 74.3 },
        { x: 64.8, y: 71.4 },
        { x: 63.3, y: 71.8 },
        { x: 61.7, y: 65.9 },
        { x: 57.2, y: 67 },
        { x: 56.9, y: 66.8 },
        { x: 55, y: 66.5 },
        { x: 54.9, y: 70.7 },
        { x: 55, y: 73.7 },
        { x: 55.1, y: 74.3 },
        { x: 55.1, y: 75.4 },
        { x: 56.9, y: 75.6 },
        { x: 56.8, y: 76.4 },
        { x: 56.1, y: 80.6 },
        { x: 57.2, y: 80.6 },
        { x: 57.3, y: 82.1 }
      ],
    },
    {
      id: "flower-garden",
      label: "Flower\nGarden",
      position: { x: 81.4, y: 76.9 },
      color: "#4ade80",
      outline: [
        { x: 70.1, y: 74.9 },
        { x: 70.1, y: 77.8 },
        { x: 72, y: 77.8 },
        { x: 72, y: 79.1 },
        { x: 72.7, y: 79.2 },
        { x: 72.7, y: 80.3 },
        { x: 73.8, y: 81.5 },
        { x: 73.8, y: 83.1 },
        { x: 74.4, y: 83.1 },
        { x: 74.4, y: 83.7 },
        { x: 73.8, y: 84.2 },
        { x: 72.7, y: 84.4 },
        { x: 72.7, y: 84.8 },
        { x: 73.9, y: 85.4 },
        { x: 73.8, y: 85.9 },
        { x: 74.6, y: 86.9 },
        { x: 75.9, y: 87.4 },
        { x: 76.8, y: 88.8 },
        { x: 78.7, y: 88.9 },
        { x: 80.5, y: 89.3 },
        { x: 81.6, y: 89.1 },
        { x: 84.5, y: 87.5 },
        { x: 85.1, y: 88.2 },
        { x: 85.7, y: 87.8 },
        { x: 85.8, y: 86.5 },
        { x: 86.2, y: 86.1 },
        { x: 87.2, y: 86.3 },
        { x: 87.6, y: 87 },
        { x: 88.6, y: 87 },
        { x: 88.8, y: 86.7 },
        { x: 89, y: 86.9 },
        { x: 90.5, y: 86 },
        { x: 92.2, y: 83.6 },
        { x: 92.4, y: 82 },
        { x: 91.7, y: 80.7 },
        { x: 90.1, y: 80.9 },
        { x: 89.4, y: 75 },
        { x: 88.8, y: 75 },
        { x: 87.9, y: 68 },
        { x: 85.6, y: 68.2 },
        { x: 85.5, y: 68.5 },
        { x: 81.3, y: 67.4 },
        { x: 81.8, y: 65 },
        { x: 76.1, y: 63.6 },
        { x: 74.4, y: 64.1 },
        { x: 75.2, y: 67.6 },
        { x: 70.8, y: 68.8 },
        { x: 71.1, y: 70.6 },
        { x: 70.4, y: 70.9 },
        { x: 70.5, y: 73.4 },
        { x: 72, y: 73.4 },
        { x: 72.1, y: 74.8 },
        { x: 70.1, y: 74.9 },
      ],
    },
    {
      id: "tea-garden",
      label: "Tea\nGarden",
      position: { x: 34.7, y: 55.1 },
      color: "#14b8a6",
      outline: [
        { x: 44, y: 48.7 },
        { x: 41.4, y: 49 },
        { x: 39.7, y: 49 },
        { x: 39.6, y: 49.7 },
        { x: 38.3, y: 50 },
        { x: 38.3, y: 50.5 },
        { x: 35.5, y: 50.3 },
        { x: 35.3, y: 48.1 },
        { x: 31.8, y: 48.2 },
        { x: 31.9, y: 49.5 },
        { x: 32.5, y: 49.6 },
        { x: 32.6, y: 50.6 },
        { x: 32, y: 50.7 },
        { x: 32.1, y: 52.6 },
        { x: 30, y: 53.3 },
        { x: 29.9, y: 54.8 },
        { x: 29.9, y: 57.6 },
        { x: 29.9, y: 59 },
        { x: 31.9, y: 60.2 },
        { x: 33.8, y: 60.3 },
        { x: 33.9, y: 61.9 },
        { x: 37, y: 61.9 },
        { x: 37.1, y: 60.3 },
        { x: 38.3, y: 60.3 },
        { x: 39.6, y: 58.5 },
        { x: 39.7, y: 54 },
        { x: 41.6, y: 54 },
        { x: 41.6, y: 52.6 },
        { x: 44.2, y: 52.7 },
        { x: 44, y: 48.7 },
      ],
    },
    {
      id: "training-area",
      label: "Training\nArea",
      position: { x: 20.4, y: 61 },
      color: "#ef4444",
      outline: [
        { x: 29.9, y: 54.7 },
        { x: 29.9, y: 59 },
        { x: 29.7, y: 61.8 },
        { x: 28, y: 61.7 },
        { x: 27.4, y: 66.1 },
        { x: 27.1, y: 68.5 },
        { x: 23.2, y: 68.1 },
        { x: 23.1, y: 68.4 },
        { x: 24, y: 68.5 },
        { x: 23.8, y: 70.2 },
        { x: 24.2, y: 70.3 },
        { x: 23.7, y: 73.9 },
        { x: 18.7, y: 73.4 },
        { x: 17.2, y: 73 },
        { x: 17.6, y: 69.5 },
        { x: 18.2, y: 67.1 },
        { x: 18.4, y: 66.6 },
        { x: 15.7, y: 65.1 },
        { x: 13.3, y: 64.8 },
        { x: 11.8, y: 64.6 },
        { x: 11.2, y: 63.6 },
        { x: 11.2, y: 62.9 },
        { x: 12.8, y: 62.1 },
        { x: 14.4, y: 61.5 },
        { x: 14.6, y: 60.6 },
        { x: 14.4, y: 59.6 },
        { x: 15.1, y: 58.6 },
        { x: 14.6, y: 56.7 },
        { x: 14.3, y: 56.2 },
        { x: 14.7, y: 55.8 },
        { x: 15.6, y: 55.9 },
        { x: 16.7, y: 55.9 },
        { x: 17.9, y: 55 },
        { x: 19.2, y: 55.2 },
        { x: 19.6, y: 55.6 },
        { x: 20.5, y: 55.4 },
        { x: 22.4, y: 55.8 },
        { x: 24.7, y: 54.9 },
        { x: 25.1, y: 54.8 },
        { x: 29.9, y: 54.7 },
      ],
    },
    {
      id: "tenshu-entrance",
      label: "Tenshu\nEntrance",
      position: { x: 50.5, y: 36.8 },
      color: "#d946ef",
      outline: [
        { x: 46.4, y: 41.6 },
        { x: 45.4, y: 36.5 },
        { x: 48.4, y: 35.8 },
        { x: 47.3, y: 29.3 },
        { x: 46.8, y: 26.3 },
        { x: 45, y: 26.6 },
        { x: 42.9, y: 14.2 },
        { x: 46.7, y: 13.6 },
        { x: 47.7, y: 19 },
        { x: 51, y: 18.4 },
        { x: 52.7, y: 27.2 },
        { x: 52, y: 27.4 },
        { x: 53, y: 33.9 },
        { x: 54.7, y: 33.7 },
        { x: 55.3, y: 37.7 },
        { x: 54.3, y: 38.8 },
        { x: 54.6, y: 40.2 },
        { x: 46.4, y: 41.6 },
      ],
    },
    {
      id: "storage-rooms",
      label: "Storage\nRooms",
      position: { x: 41, y: 22.4 },
      color: "#6366f1",
      outline: [
        { x: 36.4, y: 16.8 },
        { x: 38.4, y: 27.8 },
        { x: 37.7, y: 27.9 },
        { x: 39.3, y: 37.4 },
        { x: 45.4, y: 36.5 },
        { x: 48.4, y: 35.8 },
        { x: 46.8, y: 26.3 },
        { x: 45, y: 26.6 },
        { x: 43.6, y: 18.6 },
        { x: 43.1, y: 15.4 },
        { x: 36.4, y: 16.9 },
      ],
    },
    {
      id: "workshop",
      label: "Workshop",
      position: { x: 39.5, y: 12 },
      color: "#fb923c",
      outline: [
        { x: 43.1, y: 15.3 },
        { x: 35.4, y: 17 },
        { x: 34.9, y: 13.8 },
        { x: 34.2, y: 9.2 },
        { x: 41.8, y: 7.9 },
        { x: 42.1, y: 9.1 },
        { x: 47.7, y: 8.2 },
        { x: 48.5, y: 13.2 },
        { x: 42.9, y: 14.2 },
        { x: 43.1, y: 15.3 },
      ],
    },
    {
      id: "war-room",
      label: "War Room",
      position: { x: 53.2, y: 14.2 },
      color: "#f43f5e",
      outline: [
        { x: 51.9, y: 13 },
        { x: 61.8, y: 11.3 },
        { x: 62.5, y: 14.4 },
        { x: 55.9, y: 15.5 },
        { x: 49.2, y: 16.8 },
        { x: 48.5, y: 13.2 },
        { x: 47.7, y: 8.1 },
        { x: 47.2, y: 4.8 },
        { x: 50.5, y: 4.3 },
        { x: 51.9, y: 13 },
      ],
    },
    {
      id: "shoguns-sanctum",
      label: "Shogun's\nSanctum",
      position: { x: 56.5, y: 7.7 },
      color: "#fcd34d",
      outline: [
        { x: 50.5, y: 4.3 },
        { x: 55.6, y: 3.4 },
        { x: 60.3, y: 3.3 },
        { x: 61.8, y: 11.2 },
        { x: 52, y: 12.9 },
        { x: 50.5, y: 4.3 },
      ],
    },
    {
      // Upper-story room: overlaps Storage Rooms below it. A roof name may sit
      // above this later (see floors note).
      id: "meditation-room",
      label: "Meditation\nRoom",
      position: { x: 40.4, y: 19.3 },
      floor: "upper",
      color: "#a3e635",
      outline: [
        { x: 43.1, y: 15.3 },
        { x: 36.4, y: 16.9 },
        { x: 38.3, y: 27.5 },
        { x: 45, y: 26.4 },
      ],
    },
    {
      // Upper-story room: overlaps Storage Rooms + Tenshu Entrance.
      id: "collapsed-study",
      label: "Collapsed\nStudy",
      position: { x: 42.5, y: 31.1 },
      floor: "upper",
      color: "#c084fc",
      outline: [
        { x: 37.7, y: 27.8 },
        { x: 46.7, y: 26.4 },
        { x: 47.7, y: 31.2 },
        { x: 52.4, y: 30.3 },
        { x: 52.7, y: 32.4 },
        { x: 48, y: 33.2 },
        { x: 48.4, y: 35.8 },
        { x: 45.5, y: 36.5 },
        { x: 39.2, y: 37.4 },
        { x: 37.7, y: 27.8 },
      ],
    },
    {
      // Upper-story area above Tenshu Entrance — two disjoint footprints.
      id: "tenshu-eaves",
      label: "Tenshu\nEaves",
      position: { x: 48.6, y: 17.1 },
      floor: "upper",
      color: "#2dd4bf",
      outline: [
        [
          { x: 51, y: 18.5 },
          { x: 50.7, y: 16.5 },
          { x: 49.3, y: 16.8 },
          { x: 48.5, y: 13.2 },
          { x: 42.9, y: 14.3 },
          { x: 43.8, y: 19.7 },
          { x: 44.7, y: 19.8 },
          { x: 44.3, y: 16.3 },
          { x: 44.3, y: 15.1 },
          { x: 44.6, y: 14.9 },
          { x: 46.8, y: 14.6 },
          { x: 47.7, y: 19 },
          { x: 51, y: 18.5 },
        ],
        [
          { x: 44.3, y: 22.2 },
          { x: 45.2, y: 22.1 },
          { x: 46.2, y: 26.4 },
          { x: 45, y: 26.6 },
          { x: 44.3, y: 22.3 },
        ],
      ],
    },
    {
      id: "staging-area",
      label: "Staging\nArea",
      position: { x: 49.5, y: 72.3 },
      color: "#34d399",
      outline: [
        { x: 48.5, y: 65.3 },
        { x: 54.9, y: 65.6 },
        { x: 54.9, y: 75.1 },
        { x: 54.4, y: 75.2 },
        { x: 53.8, y: 79.9 },
        { x: 56.1, y: 80.1 },
        { x: 56, y: 80.6 },
        { x: 51.7, y: 80.7 },
        { x: 51.6, y: 82.3 },
        { x: 49.5, y: 82.4 },
        { x: 47.2, y: 83.6 },
        { x: 45.3, y: 79.1 },
        { x: 46, y: 78.6 },
        { x: 45.4, y: 75.8 },
        { x: 44.7, y: 75.9 },
        { x: 44.2, y: 73.1 },
        { x: 44.9, y: 73 },
        { x: 44.8, y: 71.7 },
        { x: 43.6, y: 71.8 },
        { x: 43.7, y: 66.8 },
        { x: 48.5, y: 66.9 },
        { x: 48.5, y: 65.3 },
      ],
    },
    {
      id: "stables",
      label: "Stables",
      position: { x: 35, y: 75 },
      color: "#eab308",
      outline: [
        { x: 24.2, y: 70.3 },
        { x: 23.8, y: 73.6 },
        { x: 26.9, y: 74 },
        { x: 26.3, y: 80.5 },
        { x: 28.2, y: 80.7 },
        { x: 30, y: 81.4 },
        { x: 30.6, y: 80.4 },
        { x: 32.3, y: 81 },
        { x: 31.6, y: 82.7 },
        { x: 33.3, y: 83.1 },
        { x: 39.3, y: 83.1 },
        { x: 39.4, y: 81.7 },
        { x: 40.4, y: 81.6 },
        { x: 40.6, y: 81.1 },
        { x: 44, y: 79.8 },
        { x: 43.4, y: 77.4 },
        { x: 42.9, y: 77.4 },
        { x: 42.8, y: 76.2 },
        { x: 44.7, y: 75.9 },
        { x: 44.2, y: 73 },
        { x: 42.4, y: 73.3 },
        { x: 42.1, y: 70.9 },
        { x: 41.1, y: 70.2 },
        { x: 39.8, y: 68 },
        { x: 39.1, y: 68 },
        { x: 39.1, y: 65.9 },
        { x: 30.7, y: 65.9 },
        { x: 30.1, y: 68.9 },
        { x: 27.5, y: 68.8 },
        { x: 27, y: 70.5 },
        { x: 24.2, y: 70.3 },
      ],
    },
    {
      id: "hillslide",
      label: "Hillslide",
      position: { x: 54.5, y: 59.9 },
      color: "#60a5fa",
      outline: [
        { x: 48.6, y: 65.2 },
        { x: 53.6, y: 65.4 },
        { x: 53.4, y: 64.3 },
        { x: 52.8, y: 64.3 },
        { x: 52.9, y: 62.9 },
        { x: 54.1, y: 62.8 },
        { x: 55.8, y: 61.8 },
        { x: 57.3, y: 59.9 },
        { x: 57, y: 58 },
        { x: 57.2, y: 56.8 },
        { x: 54, y: 56.7 },
        { x: 53.6, y: 57.6 },
        { x: 51.9, y: 59 },
        { x: 50.8, y: 61 },
        { x: 50.2, y: 62.6 },
        { x: 50, y: 64.3 },
        { x: 49.6, y: 64.7 },
        { x: 48.6, y: 65.2 },
      ],
    },
    {
      id: "onsen-baths",
      label: "Onsen\nBaths",
      position: { x: 54.8, y: 23.2 },
      color: "#aea9b1",
      outline: [
        { x: 50.7, y: 16.6 },
        { x: 52.8, y: 27.2 },
        { x: 52.2, y: 27.4 },
        { x: 53.1, y: 33.8 },
        { x: 59.5, y: 32.8 },
        { x: 58.4, y: 26.3 },
        { x: 57.8, y: 26.5 },
        { x: 56, y: 15.7 },
        { x: 50.7, y: 16.6 }
      ]
    },
  ],

  // ── Easter eggs ─────────────────────────────────────────────────────────
  // Each egg's `steps` reference a marker by `markerId` so selecting a step
  // focuses + reveals that location. Add steps once the markers exist.
  eggs: [
    {
      id: "main-quest",
      name: "Main Quest",
      color: "#ec4899",
      stages: [
        {
          id: "stage-1",
          title: "Acquire the World Seed",
          steps: [
            {
              id: "s1-kitchens",
              title: "Recapture the Ward — Kitchens",
              instruction:
                "Recapture the Ward in the Kitchens by standing next to the dragon banner while fending off zombies.",
              icon: "/images/easteregg/dragonicon.png",
              revealImages: ["/images/easteregg/stage_01/stage_01_step_01_a.jpg", "/images/easteregg/stage_01/stage_01_step_01_b.jpg"],
              // Route: spawn → … → dragon banner in the Kitchens (last point).
              path: [
                { x: 52.4, y: 94.5 },
                { x: 58.5, y: 82.4 },
                { x: 60, y: 76.7 },
                { x: 82.2, y: 76.7 },
                { x: 84, y: 60.8 },
                { x: 79.5, y: 58.8 },
                { x: 74.5, y: 51.1 },
              ],
            },
            {
              id: "s1-training",
              title: "Recapture the Ward — Training Area",
              instruction:
                "Recapture the Ward in the Training Area by standing next to the dragon banner while fending off zombies.",
              icon: "/images/easteregg/dragonicon.png",
              revealImages: ["/images/easteregg/stage_01/stage_01_step_02_a.jpg", "/images/easteregg/stage_01/stage_01_step_02_b.jpg"],
              path: [
                { x: 74.3, y: 52 },
                { x: 66, y: 55 },
                { x: 61.3, y: 51.3 },
                { x: 44.6, y: 50.6 },
                { x: 28.8, y: 56.6 },
                { x: 18.8, y: 60.7 },
              ],
            },
            {
              id: "s1-hanko",
              title: "Acquire the Shogun's Hanko",
              instruction:
                "Defeat the Oni in the War Room and collect Shogun's Hanko.",
              icon: "/images/easteregg/star.svg",
              revealImages: ["/images/easteregg/stage_01/stage_01_step_03_a.jpg", "/images/easteregg/stage_01/stage_01_step_03_b.jpg", "/images/easteregg/stage_01/stage_01_step_03_c.jpg", "/images/easteregg/stage_01/stage_01_step_03_d.jpg"],
              revealCaption:
                "**Route:** On the way to the **War Room**, detour through **PHD Flopper**; you will need it later.\n\n**Fight:** Enter the **War Room** and defeat the armoured zombies and the Oni.\n\n**Finish:** The Oni drops **Shogun's Hanko**. Collect it, then open the door to the **Shogun's Sanctum**.",
              path: [
                { x: 18.8, y: 60.4 },
                { x: 44.5, y: 49.8 },
                { x: 50.3, y: 34.5 },
                { x: 48.8, y: 29.4 },
                { x: 42.7, y: 30.7 },
                { x: 37.9, y: 15.1 },
                { x: 47.8, y: 10.8 },
                { x: 52.3, y: 10.1 },
              ],
            },
            {
              id: "s1-ceramic-shard",
              title: "Broken Ceramic Shard",
              instruction:
                "Find the ceramic shard near the pool of blood by the Pack-a-Punch stairs.",
              icon: "/images/easteregg/star.svg",
              iconPosition: { x: 49.7, y: 7.6 },
              revealImages: ["/images/easteregg/stage_04/stage_04_step_03_a.jpg", "/images/easteregg/stage_04/stage_04_step_03_b.jpg"],
            },
            {
              id: "s1-unlock-pap",
              title: "Unlock Pack-a-Punch",
              instruction:
                "Defeat zombies around the world seed to unlock Pack-a-Punch.",
              icon: "/images/easteregg/star.svg",
              revealImages: ["/images/easteregg/stage_01/stage_01_step_04_a.jpg", "/images/easteregg/stage_01/stage_01_step_04_b.jpg", "/images/easteregg/stage_01/stage_01_step_04_c.jpg"],
              revealCaption:
                "**World Seed:** Walk up the stairs to the seed beside **Pack-a-Punch**.\n\nLure zombies close enough that they glow purple, then kill them near the seed to charge it. When the charge is complete, **Pack-a-Punch** unlocks.",
              path: [
                { x: 52.3, y: 10.1 },
                { x: 58.8, y: 8.3 },
              ],
            },
          ],
        },
        {
          id: "stage-2",
          title: "Obtain the Nekomancer Wonder Weapon",
          steps: [
            {
              id: "s2-furin",
              title: "Find the Furin (Bell)",
              instruction:
                "Find the Furin (Bell) in one of three locations: Staging Area, Stables, or Training Area.",
              locations: [
                {
                  text: "Training Area",
                  position: { x: 18.6, y: 66.7 },
                  revealImage: "/images/easteregg/stage_02/stage_02_step_01_loc_01.jpg",
                },
                {
                  text: "Stables",
                  position: { x: 36.6, y: 70.4 },
                  revealImage: "/images/easteregg/stage_02/stage_02_step_01_loc_02.jpg",
                },
                {
                  text: "Staging Area",
                  position: { x: 49.4, y: 82.2 },
                  revealImage: "/images/easteregg/stage_02/stage_02_step_01_loc_03.jpg",
                },
              ],
            },
            {
              id: "s2-maneki-neko",
              title: "Obtain the Maneki-Neko (Cat Statue)",
              instruction:
                "Find the Maneki-Neko (Cat Statue) in one of three marked spots in the Gatehouse or Kitchens.",
              locations: [
                { position: { x: 60.5, y: 70.2 }, revealImages: ["/images/easteregg/stage_02/stage_02_step_02_loc_01_a.jpg", "/images/easteregg/stage_02/stage_02_step_02_loc_01_b.jpg"] },
                { position: { x: 74, y: 49.5 }, revealImages: ["/images/easteregg/stage_02/stage_02_step_02_loc_02_a.jpg"] },
                { position: { x: 87.4, y: 54.9 }, revealImages: ["/images/easteregg/stage_02/stage_02_step_02_loc_03_a.jpg"] },
              ],
            },
            {
              id: "s2-karakuri",
              title: "Get the Karakuri (Doll)",
              instruction:
                "Find the Karakuri (Doll) in one of the marked Storage Rooms or Workshop spots.",
              locations: [
                { position: { x: 35.8, y: 14.4 }, revealImage: "/images/easteregg/stage_02/stage_02_step_03_loc_01.jpg" },
                { position: { x: 43.6, y: 19.9 }, revealImage: "/images/easteregg/stage_02/stage_02_step_03_loc_02.jpg" },
                { position: { x: 45.6, y: 29.6 }, revealImage: "/images/easteregg/stage_02/stage_02_step_03_loc_03.jpg" },
              ],
            },
            {
              id: "s2-craft-maneki-neko",
              title: "Craft the Maneki-Neko",
              instruction:
                "Craft the Maneki-Neko on the worktable in the Workshop.",
              icon: "/images/easteregg/craft.svg",
              iconPosition: { x: 44.7, y: 9.3 },
              revealImage: "/images/easteregg/stage_02/stage_02_step_04.jpg",
              revealCaption:
                "**Workshop:** With all three parts collected, craft the **Maneki-Neko** on the worktable to the left of **Vulture Aid**.\n\nPick it up once crafting finishes.\n\n**Important:** The Maneki-Neko is tactical equipment used later. If you use it, you can recraft another one at this bench.",
            },
            {
              id: "s2-cage",
              title: "Get the Cage at the Castle",
              instruction:
                "Drop the cage from the Tenshu Eaves using PHD Flopper, then collect it.",
              icon: "/images/easteregg/star.svg",
              revealImages: ["/images/easteregg/stage_02/stage_02_step_05_a.jpg", "/images/easteregg/stage_02/stage_02_step_05_b.jpg"],
              iconPosition: { x: 45.5, y: 23.9 },
              revealCaption:
                "**Tenshu Entrance:** Find the cage near the cherry blossom tree.\n\nGet **PHD Flopper** from the **Storage Rooms**, then dolphin-dive under the cage so the landing explosion knocks it down. Collect the cage after it drops.",
            },
            {
              id: "s2-lava",
              title: "Throw the Cage into Lava",
              instruction:
                "Once you have the cage, throw it into lava to free the cat.",
              icon: "/images/easteregg/flame.svg",
              iconPosition: { x: 18.3, y: 55.3 },
              revealImage: "/images/easteregg/stage_02/stage_02_step_06.jpg",
              revealCaption:
                "Pick up the cage and throw it into any body of **lava** to destroy the cage and free the cat.\n\n**Note:** Some lava can harden temporarily, but the outer lava areas never fully seal and can always be used.",
            },
            {
              id: "s2-paw-prints",
              title: "Follow the Paw Prints",
              instruction:
                "Follow and clear the paw-print trails in one of four locations: Training Area, Stables, Flower Garden, or Kitchens.",
              // Each location is a trail with a glowing paw print at both ends.
              // Clicking the start end opens image 1; the far end opens image 2.
              locations: [
                {
                  label: "1",
                  color: "#fb923c",
                  icon: "/images/easteregg/paw.svg",
                  path: [
                    { x: 66.4, y: 54.2 },
                    { x: 78.3, y: 50.6 },
                    { x: 82, y: 52.1 },
                  ],
                  // Trail start only; the end is Step 8's skull (combined there).
                  //revealImage: "/images/easteregg/stage-2/step7-loc1-start.jpg",
                },
                {
                  label: "2",
                  color: "#fb923c",
                  icon: "/images/easteregg/paw.svg",
                  path: [{ x: 83.6, y: 69 }],
                  //revealImage: "/images/easteregg/stage-2/step7-loc2-start.jpg",
                },
                {
                  label: "3",
                  color: "#fb923c",
                  icon: "/images/easteregg/paw.svg",
                  path: [
                    { x: 43, y: 74.8 },
                    { x: 40.6, y: 75.4 },
                    { x: 39.5, y: 80.7 },
                    { x: 33.2, y: 80.6 },
                    { x: 31.9, y: 76.1 },
                  ],
                  //revealImage: "/images/easteregg/stage-2/step7-loc3-start.jpg",
                },
                {
                  label: "4",
                  color: "#fb923c",
                  icon: "/images/easteregg/paw.svg",
                  path: [
                    { x: 23.8, y: 71.5 },
                    { x: 14.6, y: 62.3 },
                  ],
                  revealImages: ["/images/easteregg/stage_02/stage_02_step_07_loc_04_start_a.jpg", "/images/easteregg/stage_02/stage_02_step_07_loc_04_start_b.jpg"],
                },
              ],
            },
            {
              id: "s2-abomination",
              title: "Kill the Abomination",
              instruction:
                "Throw the Maneki-Neko at the end of your paw-print trail into the center of the converging paws to spawn the Abomination, then defeat it to free the cat. The game assigns one of the four trails at random each match.",
              // One skull per Step 7 trail END (you only get one per game). Each
              // reveal combines that trail's end shot with the Abomination shot.
              locations: [
                {
                  label: "1",
                  color: "#ef4444",
                  icon: "/images/easteregg/skull.svg",
                  position: { x: 82, y: 52.1 },
                  /* revealImages: [
                   "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_a.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_b.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_c.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_d.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_e.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_f.jpg"
                  ], */
                },
                // Trail 2 end: TBD (trail 2 path not provided yet).
                {
                  label: "3",
                  color: "#ef4444",
                  icon: "/images/easteregg/skull.svg",
                  position: { x: 31.9, y: 76.1 },
                  /* revealImages: [
                   "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_a.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_b.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_c.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_d.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_e.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_f.jpg"
                  ], */
                },
                {
                  label: "4",
                  color: "#ef4444",
                  icon: "/images/easteregg/skull.svg",
                  position: { x: 14.6, y: 62.3 },
                  revealImages: [
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_a.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_b.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_c.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_d.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_e.jpg",
                    "/images/easteregg/stage_02/stage_02_step_08_loc_04_end_f.jpg"
                  ],
                },
              ],
            },
            {
              id: "s2-capture-cat",
              title: "Capture the Cat",
              instruction:
                "Quietly find and capture the cat in the Kitchens (2 spots) or the Training Area (1 spot).",
              revealCaption:
                "**Required perk:** Get **Death Perception** before searching for the cat.\n\nSearch the **Kitchens** or **Training Area**. The marked spots have creaky floorboards that make noise when stepped on, and Death Perception highlights them in orange.\n\nCrouch-walk early, avoid the noisy boards, then crouch beside the cat and interact to pick it up.",
              locations: [
                { label: "1", position: { x: 76.6, y: 42 }, revealImage: "/images/easteregg/stage_02/stage_02_step_09_loc_01.jpg" },
                { label: "2", position: { x: 87, y: 61.3 }, revealImage: "/images/easteregg/stage_02/stage_02_step_09_loc_02.jpg" },
                { label: "3", position: { x: 27.2, y: 62.6 }, revealImage: "/images/easteregg/stage_02/stage_02_step_09_loc_03.jpg" },
              ],
            },
            {
              id: "s2-get-nekomancer",
              title: "Get the Nekomancer",
              instruction:
                "Take the cat to the World Seed and melee the seed between pulses, then collect the Nekomancer.",
              icon: "/images/easteregg/star.svg",
              iconPosition: { x: 58.7, y: 8.2 },
              revealImages: [
                "/images/easteregg/stage_02/stage_02_step_10_a.jpg",
                "/images/easteregg/stage_02/stage_02_step_10_b.jpg",
                "/images/easteregg/stage_02/stage_02_step_10_c.jpg",
                "/images/easteregg/stage_02/stage_02_step_10_d.jpg",
              ],
              revealCaption:
                "**Shogun's Sanctum:** Bring the cat back to the **World Seed** beside **Pack-a-Punch**. It will jump onto the seed automatically.\n\nWhen the seed glows red, it emits damaging shockwaves. Move in between shockwaves and melee the seed.\n\nAfter enough hits, the cat jumps off and drops nearby as the **Nekomancer Wonder Weapon**. When Pack-a-Punched, it becomes **Tsunderera-Hime**.",
            },
          ],
        },
        {
          id: "stage-3",
          title: "Light the Lanterns",
          steps: [
            {
              id: "s3-lanterns",
              title: "Light the Lanterns",
              instruction:
                "With the Nekomancer, light all 11 lanterns in order — without missing a shot and within the time limit. Failing means waiting for the next round to retry.",
              color: "#fbbf24",
              solidMarkers: true,
              // The route to follow; the start dot is the first point. Lanterns
              // are the numbered markers below (lantern 1 sits just off-route).
              path: [
                { x: 22, y: 57 },
                { x: 24.4, y: 59.2 },
                { x: 31.9, y: 57.1 },
                { x: 32.7, y: 51.4 },
                { x: 48.9, y: 49.4 },
                { x: 47.8, y: 39.9 },
                { x: 51.8, y: 28.2 },
                { x: 48.2, y: 40.7 },
                { x: 59.6, y: 53.5 },
                { x: 62.1, y: 51.8 },
                { x: 65.9, y: 54.4 },
                { x: 73.4, y: 55.7 },
                { x: 79.5, y: 57.2 },
                { x: 80, y: 59.5 },
                { x: 85, y: 61.8 },
                { x: 81.5, y: 74.6 },
                { x: 75, y: 78.7 },
                { x: 71, y: 76.3 },
                { x: 60.5, y: 73.3 },
                { x: 56.2, y: 73.4 },
                { x: 58.8, y: 74.7 },
                { x: 57.8, y: 83.6 },
                { x: 51, y: 88.1 },
                { x: 47.5, y: 74.8 },
                { x: 48.7, y: 69.3 },
                { x: 44.7, y: 74.4 },
                { x: 38.7, y: 75.6 },
                { x: 35, y: 78.9 },
              ],
              locations: [
                { label: "1", position: { x: 22, y: 52.9 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_01.jpg" },
                { label: "2", position: { x: 32.7, y: 51.4 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_02.jpg" },
                { label: "3", position: { x: 48.9, y: 49.4 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_03.jpg" },
                { label: "4", position: { x: 51.8, y: 28.2 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_04.jpg" },
                { label: "5", position: { x: 59.6, y: 53.5 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_05.jpg" },
                { label: "6", position: { x: 73.4, y: 55.7 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_06.jpg" },
                { label: "7", position: { x: 75, y: 78.7 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_07.jpg" },
                { label: "8", position: { x: 56.2, y: 73.4 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_08.jpg" },
                { label: "9", position: { x: 51, y: 88.1 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_09.jpg" },
                { label: "10", position: { x: 48.7, y: 69.3 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_10.jpg" },
                { label: "11", position: { x: 35, y: 78.9 }, revealImage: "/images/easteregg/stage_03/stage_03_step_01_lantern_11.jpg" },
              ],
            },
            {
              id: "s3-war-room-cutscene",
              title: "War Room Cut-Scene",
              instruction:
                "Step into the blood on the War Room floor to trigger the cut-scene.",
              icon: "/images/easteregg/star.svg",
              iconPosition: { x: 51, y: 10 },
              revealImages: ["/images/easteregg/stage_03/stage_03_step_02_a.jpg",
                "/images/easteregg/stage_03/stage_03_step_02_b.jpg",
                "/images/easteregg/stage_03/stage_03_step_02_c.jpg"
              ],
            },
          ],
        },
        {
          id: "stage-4",
          title: "Fox Mask",
          steps: [
            {
              id: "s4-obtain-fox-mask",
              title: "Obtain the Fox Mask",
              instruction:
                "Fly the ninja kite from atop the Shogun's Sanctum, take the right path past the tree, and spam interact to grab the Fox Mask.",
              revealCaption:
                "**Shogun's Sanctum:** Turn around and exit through the blasted-out wall that leads to the castle roof.\n\nOutside, look left for the carp-shaped windsocks; this is the **Ninja Kite**. While gliding, steer right until you pass to the right of the large tree.\n\nOnce you are on the right-hand path, spam interact to grab the **Fox Mask** from the castle roof edge. A notification appears when you pick it up.",
              // Both markers are mandatory → solid circles (route stays dotted).
              solidMarkers: true,
              path: [
                { x: 47.7, y: 12.6 },
                { x: 43.7, y: 57.7 },
              ],
              locations: [
                { label: "1", position: { x: 47.7, y: 12.6 }, revealImages: ["/images/easteregg/stage_04/stage_04_step_01_a.jpg", "/images/easteregg/stage_04/stage_04_step_01_b.jpg", "/images/easteregg/stage_04/stage_04_step_01_c.jpg", "/images/easteregg/stage_04/stage_04_step_01_d.jpg"] },
                { label: "2", position: { x: 43.7, y: 57.7 }, revealImages: ["/images/easteregg/stage_04/stage_04_step_01_d.jpg"] },
              ],
            },
            {
              id: "s4-fox-mask-minigame",
              title: "Fox Mask Mini-Game",
              instruction:
                "Interact with the mask wall and kill the zombies matching the order of the masks until the cutscene.",
              revealCaption:
                "**Storage Rooms:** Bring the **Fox Mask** to the mask wall and start the minigame.\n\nThe masks glow blue in a sequence, then zombies spawn wearing matching masks. Kill the masked zombies in the same order the wall masks glowed. Complete three rounds to finish the step.\n\n**Failure rules:** Shooting the zombies out of order fails the attempt. Leaving the Storage Rooms also fails it.\n\n**Tip:** Shock Charges and Stun Grenades help hold zombies still. Avoid Aether Shroud because it can make the zombies leave the area.\n\nWhen complete, interact with the mask at the bottom of the wall to trigger the cutscene. The Fox Mask then flies to one of the next locations.",
               solidMarkers: true,
                locations: [
                { label: "1", position: { x: 42.9, y: 25 }, revealImages: ["/images/easteregg/stage_04/stage_04_step_02_a.jpg", "/images/easteregg/stage_04/stage_04_step_02_b.jpg", "/images/easteregg/stage_04/stage_04_step_02_c.jpg", "/images/easteregg/stage_04/stage_04_step_02_d.jpg", "/images/easteregg/stage_04/stage_04_step_02_e.jpg"] },
              ],
            },
          ],
        },
        {
          id: "stage-5",
          title: "Collect the Evidences",
          steps: [
            {
              id: "s5-suspect-evidences",
              title: "Suspect Evidences",
              instruction:
                "Find the masks in three rooms (Collapsed Study, Workshop, Onsen Baths) and return them to the Meditation Room.",
              revealCaption:
                "**Meditation Room:** The evidences are placed on the shelves inside this room.\n\nShoot the moving **Fox Mask** when it hides around the map. Each hit drops one evidence item.\n\n- **Takeshi's Pipe:** Bottom shelf left of the stairs in the **Workshop**.\n- **Takeo's Case:** In the ceiling of the **Collapsed Study**.\n- **Mitsuhime's Comb:** Far left, outside the window left of **Elemental Pop** in the **Onsen Baths**.\n\nPlace all three evidences on the Meditation Room shelves. When done correctly, a painting of a person wearing the fox mask appears on the other side of the room.",
              solidMarkers: true,
              locations: [
                { label: "1", position: { x: 36, y: 13.1 }, revealImages: ["/images/easteregg/stage_05/stage_05_step_01_a.jpg", "/images/easteregg/stage_05/stage_05_step_01_aa.jpg"] },
                { label: "2", position: { x: 41, y: 35.1 }, revealImages: ["/images/easteregg/stage_05/stage_05_step_01_b.jpg", "/images/easteregg/stage_05/stage_05_step_01_bb.jpg"] },
                { label: "3", position: { x: 56.1, y: 18.5 }, revealImages: ["/images/easteregg/stage_05/stage_05_step_01_c.jpg", "/images/easteregg/stage_05/stage_05_step_01_cc.jpg"] },
                { label: "4", position: { x: 38.2, y: 20 }, revealImages: ["/images/easteregg/stage_05/stage_05_step_01_d.jpg", "/images/easteregg/stage_05/stage_05_step_01_e.jpg", "/images/easteregg/stage_05/stage_05_step_01_f.jpg"] },
              ],
            },
            {
              // "Accomplice Evidences" has three sub-tasks (Merchant, Gardener,
              // TBD). Modeled as one step per accomplice for clean grouping.
              id: "s5-accomplice-merchant",
              title: "Accomplice Evidences: Merchant",
              instruction:
                "Track down the Merchant to collect the note and Mercantile Abacus. Select this step for the sub-steps.",
              solidMarkers: true,
              locations: [
                {
                  label: "1",
                  text: "Look for the Mystery Box with the Japanese wooden plaque on its base, then move the box to this spot.",
                  revealCaption:
                    "**Mystery Box:** Find the box with the Japanese wooden plaque on its base.\n\nMove that Mystery Box to the marked spot before continuing.",
                  // Placed off-map (bottom-left margin) — the box can be anywhere.
                  position: { x: 15, y: 90 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_02_merch_01_a.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_01_b.jpg"],
                },
                {
                  label: "2",
                  text: "Throw the Maneki-Neko in front of the box while using the Mystery Box. Done correctly, the Coin Purse becomes available to pick up.",
                  revealCaption:
                    "**Mystery Box:** Throw the **Maneki-Neko** in front of the box while using it.\n\nIf done correctly, the **Coin Purse** becomes available to pick up.",
                  position: { x: 15, y: 94 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_02_merch_02_a.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_02_b.jpg"],
                },
                {
                  label: "3",
                  text: "Travel to the Outer Ward and place the Coin Purse to the right of the Rampage Inducer, then interact again to trigger a short cinematic.",
                  revealCaption:
                    "**Outer Ward:** Place the **Coin Purse** to the right of the Rampage Inducer.\n\nInteract again after placing it to trigger the short cinematic.",
                  position: { x: 52.5, y: 95.4 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_02_merch_03_a.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_03_b.jpg"],
                },
                {
                  label: "4",
                  text: "In the Kitchens, knock a fruit from the basket on top of a shelf. Once per round a zombie eats the fruit and keeps it in its mouth, then follows you around.",
                  revealCaption:
                    "**Kitchens:** Knock a fruit from the basket on top of the shelf.\n\nOnce per round, a zombie eats the fruit, keeps it in its mouth, and follows you around. Lead that zombie to the next marked spot.",
                  path: [
                    { x: 84.9, y: 45.4 },
                    { x: 78.1, y: 43.4 },
                    { x: 75.7, y: 53.3 },
                    { x: 65.9, y: 54.7 },
                    { x: 61.5, y: 51 },
                    { x: 55.9, y: 56.5 },
                    { x: 51.7, y: 63.9 },
                    { x: 51.5, y: 68.5 },
                    { x: 47.9, y: 69.7 },
                  ],
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_02_merch_04_a.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_04_b.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_04_c.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_04_d.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_04_e.jpg"],
                },
                {
                  label: "5",
                  text: "Lead the zombie to the Staging Area and kill it next to the shack's window. Done correctly, the Merchant spawns — kill it to collect the note and the Mercantile Abacus.",
                  revealCaption:
                    "**Staging Area:** Lead the fruit-carrying zombie to the shack window and kill it there.\n\nIf done correctly, the **Merchant** spawns. Kill the Merchant to collect the note and **Mercantile Abacus**.",
                  position: { x: 47.9, y: 69.7 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_02_merch_05_a.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_05_b.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_05_c.jpg", "/images/easteregg/stage_05/stage_05_step_02_merch_05_d.jpg"],
                },
              ],
            },
            {
              id: "s5-accomplice-gardener",
              title: "Accomplice Evidences: Gardener",
              instruction:
                "Fill a bucket, water the three Flower Garden plants, then break the Gardener's immunity to collect its evidence. Select this step for the sub-steps.",
              locations: [
                {
                  label: "1",
                  text: "Collect the bucket from either a Tea Garden cupboard or the top floor of the Onsen Baths.",
                  revealCaption:
                    "**Bucket:** Collect it from either a cupboard in the **Tea Garden** or the top floor of the **Onsen Baths**.",
                  solid: false,
                  positions: [
                    { x: 33, y: 50.4 },
                    { x: 53, y: 28.3 },
                  ],
                  positionImageIndices: [0, 1],
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_01_a.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_01_c.jpg",
                  ],
                },
                {
                  label: "2",
                  text: "Interact with either pool in those locations to fill the bucket. It holds three water charges; running, sprinting, or getting hit removes one charge.",
                  revealCaption:
                    "**Fill the bucket:** Interact with either marked pool.\n\nThe bucket holds **three water charges**. Running, sprinting, or getting hit removes one charge, so move carefully after filling it.",
                  solid: false,
                  positions: [
                    { x: 33, y: 54.9 },
                    { x: 56.1, y: 31.5 },
                  ],
                  positionImageIndices: [0, 1],
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_01_b.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_01_d.jpg",
                  ],
                },
                {
                  label: "3",
                  text: "Bring the bucket to the Flower Garden and water the three plants along the cobblestone path.",
                  revealCaption:
                    "**Flower Garden:** Bring the filled bucket to the cobblestone path and water the three marked plants in order.\n\nEach numbered marker opens the matching plant screenshot.",
                  solid: true,
                  // Middle plant coordinate TBD.
                  positions: [
                    { x: 84.6, y: 72.2 },
                    { x: 87.6, y: 78 },
                    { x: 77, y: 82.5 },
                  ],
                  positionLabels: ["1", "2", "3"],
                  positionImageIndices: [0, 1, 2],
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_02_a.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_02_b.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_02_c.jpg",
                  ],
                },
                {
                  label: "4",
                  text: "The Gardener attacks while immune. Shoot the glowing flower next to each doorway to briefly remove its immunity, then kill it and collect the evidence.",
                  revealCaption:
                    "**Gardener fight:** The Gardener starts immune.\n\nShoot the glowing flower beside each doorway to briefly remove its immunity. Use that window to damage the Gardener, then kill it and collect the evidence.",
                  solid: true,
                  positions: [
                    { x: 72.8, y: 73 },
                    { x: 81.1, y: 68.3 },
                  ],
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_03_a.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_03_b.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_03_c.jpg",
                    "/images/easteregg/stage_05/stage_05_step_02_gardener_03_d.jpg",
                  ],
                },
              ],
            },
            {
              id: "s5-poison-monkshood",
              title: "Poison Evidences: Monkshood Flower",
              instruction:
                "Gather the pouch, ash, and bud, then plant and grow the Monkshood Flower. Select this step for the sub-steps.",
              solidMarkers: true,
              locations: [
                {
                  label: "1",
                  text: "Collect the Empty Pouch by hitting the wooden beam above the Ammo Cache in the Training Area with a charged Nekomancer shot or a grenade. Done correctly, the Empty Pouch drops to the ground.",
                  revealCaption:
                    "**Training Area:** Hit the wooden beam above the Ammo Cache with a charged **Nekomancer** shot or a grenade.\n\nIf done correctly, the **Empty Pouch** drops to the ground.",
                  position: { x: 25.7, y: 61.4 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_03_flower_01_a.jpg", "/images/easteregg/stage_05/stage_05_step_03_flower_01_b.jpg"],
                },
                {
                  label: "2",
                  text: "When a Fissure becomes active on the map, stay near it until the Volcanic Ash is collected. Move in and out of it to minimise damage.",
                  revealCaption:
                    "**Volcanic Ash:** Wait for a Fissure to become active, then stay near it until the ash is collected.\n\nMove in and out of the Fissure to manage damage.",
                  // Fissures are random — placed off-map (bottom-left margin).
                  position: { x: 15, y: 90 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_03_flower_02_a.jpg", "/images/easteregg/stage_05/stage_05_step_03_flower_02_b.jpg"],
                },
                {
                  label: "3",
                  text: "Collect the Monkshood Bud from the ground near the lava river and broken bridge in the Flower Garden.",
                  revealCaption:
                    "**Flower Garden:** Collect the **Monkshood Bud** from the ground near the lava river and broken bridge.",
                  position: { x: 77.8, y: 75.5 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_03_flower_03_a.jpg", "/images/easteregg/stage_05/stage_05_step_03_flower_03_b.jpg"],
                },
                {
                  label: "4",
                  text: "Plant the Monkshood Bud in a pot in a corner near the Exfil phone booth in the Tenshu Entrance, then place the Volcanic Ash on the pot.",
                  revealCaption:
                    "**Tenshu Entrance:** Plant the **Monkshood Bud** in the pot near the Exfil phone booth, then place the **Volcanic Ash** on the pot.",
                  position: { x: 46, y: 37 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_03_flower_04_a.jpg", "/images/easteregg/stage_05/stage_05_step_03_flower_04_b.jpg"],
                },
                {
                  label: "5",
                  text: "Melee a cherry blossom tree until it and you glow, then return to the pot and spin around until a small tornado appears. Done correctly, the Monkshood Flower can be picked up.",
                  revealCaption:
                    "**Grow the flower:** Melee a cherry blossom tree until both you and the tree glow.\n\nReturn to the pot and spin around until a small tornado appears. If done correctly, the **Monkshood Flower** can be picked up.",
                  position: { x: 42.5, y: 39.7 },
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_03_flower_05_a.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_flower_05_b.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_flower_05_c.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_flower_05_d.jpg",
                  ],
                },
              ],
            },
            {
              id: "s5-poison-plum",
              title: "Poison Evidences: Plum Pit",
              instruction:
                "Knock the plum loose in the Kitchens, then jump on it to make the Plum Pit.",
              solidMarkers: true,
              locations: [
                {
                  label: "1",
                  text: "Travel to the Kitchens and melee the small basket on top of a shelf near the fire pit to drop a plum. Then repeatedly jump on the plum until it becomes the Plum Pit, and collect it.",
                  revealCaption:
                    "**Kitchens:** Melee the small basket on the shelf near the fire pit to drop a plum.\n\nJump on the plum repeatedly until it becomes the **Plum Pit**, then collect it.",
                  position: { x: 77.5, y: 42.6 },
                  revealImages: [
                    "/images/easteregg/stage_05/stage_05_step_03_plum_01_a.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_plum_01_b.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_plum_01_c.jpg",
                    "/images/easteregg/stage_05/stage_05_step_03_plum_01_d.jpg",
                  ],
                },
              ],
            },
            {
              id: "s5-motive-evidences",
              title: "Motive Evidences",
              instruction:
                "Collect the Shogun's Hanko and the Netsuke of Brothers.",
              solidMarkers: true,
              locations: [
                {
                  label: "1",
                  text: "Collect the Shogun's Hanko from killing the first Oni (completed in Stage 1, Step 3).",
                  revealCaption:
                    "**Shogun's Hanko:** This is collected from the first Oni during **Stage 1, Step 3**.",
                  position: { x: 52.3, y: 10.1 },
                  revealImage: "/images/easteregg/stage_01/stage_01_step_03_c.jpg",
                },
                {
                  label: "2",
                  text: "Collect the Netsuke of Brothers: wait for the lava to harden, find the tiny statue in the Stables, throw a Molotov at it, then collect it.",
                  revealCaption:
                    "**Stables:** Wait for the lava to harden, then find the tiny statue.\n\nThrow a **Molotov** at it, then collect the **Netsuke of Brothers**.",
                  position: { x: 36, y: 76 },
                  revealImages: ["/images/easteregg/stage_05/stage_05_step_05_brothers_01_a.jpg", "/images/easteregg/stage_05/stage_05_step_05_brothers_01_b.jpg", "/images/easteregg/stage_05/stage_05_step_05_brothers_01_c.jpg"],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default kowakujo;
